AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 50
  Exclude:
    - spec/render/text/helper/*.rb

Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: true
